### ISSUE TITLE
About Fsl,Fsp's dimension

### ISSUE THREAD

**Issue by ShangDongChu** [LancasterLi/RefSAM#6]
Thanks for your excellent work, Can you provide more description about the dimension of Fsl, Fsp in section _**3.5.2 Dense Attention**_ and how do you compute the similarity Fsp?

**Comment by LancasterLi** [comment]
1. **Dimensions of Fsl and Fsp:**
   - **Fsp**: The dimension of Fsp is $(c_{v}, c_{v})$, where $c_v$ represents the dimension of the image feature from the SAM encoder.
   - **Fsl**: The dimension of Fsl is ($(N+1) \times c_v$).

2. **Computation of Similarity for Fsp**:
   - The similarity for Fsp is computed by performing a dot product between $F_{fix}$ and $F_{vt}$.
